apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: integration-ingress
  namespace: integration-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: integration-gateway.local
    http:
      paths:
      - path: /zone(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: zone-core-svc
            port:
              number: 80
      - path: /clientes(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: mc-clientes-svc
            port:
              number: 80
      - path: /notifications(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: notification-svc
            port:
              number: 80
      - path: /tickets(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ms-tickets-svc
            port:
              number: 80
